news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.type-article  a'
      article_body: '.field-name-body'
      article_title: '.h1'
  elpais:
    url: https://elpais.com
    queries: 
      homepage_article_links: '.headline > a'
      article_body: '.article_body'
      article_title: '#article_header h1'
